# Define the pipeline
stages:
  - build
  - test

# Define the jobs
build:
  stage: build
  image: gradle:jdk17
  script:
    - gradle build

test:
  stage: test
  image: gradle:jdk17
  script:
    - gradle test
